// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cdp} from '../models';

export function ClearHighlight(arg1:string):Promise<void>;

export function ConnectToChrome(arg1:string):Promise<void>;

export function DisconnectFromChrome():Promise<void>;

export function GetChildNodes(arg1:string,arg2:number):Promise<Array<cdp.DOMNode>>;

export function GetDOMTree(arg1:string):Promise<cdp.DOMNode>;

export function GetNodePath(arg1:string,arg2:number):Promise<Array<number>>;

export function GetTabs():Promise<Array<cdp.TabInfo>>;

export function HighlightNode(arg1:string,arg2:number):Promise<void>;

export function IsConnected():Promise<boolean>;

export function RunJS(arg1:string):Promise<void>;

export function SearchDOM(arg1:string,arg2:string):Promise<Array<cdp.SearchResult>>;
