// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHighlight(arg1) {
  return window['go']['main']['App']['ClearHighlight'](arg1);
}

export function ConnectToChrome(arg1) {
  return window['go']['main']['App']['ConnectToChrome'](arg1);
}

export function DisconnectFromChrome() {
  return window['go']['main']['App']['DisconnectFromChrome']();
}

export function EnableNetwork(arg1) {
  return window['go']['main']['App']['EnableNetwork'](arg1);
}

export function GetChildNodes(arg1, arg2) {
  return window['go']['main']['App']['GetChildNodes'](arg1, arg2);
}

export function GetCookies(arg1) {
  return window['go']['main']['App']['GetCookies'](arg1);
}

export function GetDOMTree(arg1) {
  return window['go']['main']['App']['GetDOMTree'](arg1);
}

export function GetLocalStorage(arg1) {
  return window['go']['main']['App']['GetLocalStorage'](arg1);
}

export function GetNodePath(arg1, arg2) {
  return window['go']['main']['App']['GetNodePath'](arg1, arg2);
}

export function GetSessionStorage(arg1) {
  return window['go']['main']['App']['GetSessionStorage'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function HighlightNode(arg1, arg2) {
  return window['go']['main']['App']['HighlightNode'](arg1, arg2);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function RunJS(arg1) {
  return window['go']['main']['App']['RunJS'](arg1);
}

export function SearchDOM(arg1, arg2) {
  return window['go']['main']['App']['SearchDOM'](arg1, arg2);
}
