// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cdp} from '../models';

export function CaptureScreenshot(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<string>;

export function ClearHighlight(arg1:string):Promise<void>;

export function ClearNetworkCache():Promise<void>;

export function CollectWebVitals(arg1:string):Promise<cdp.WebVitals>;

export function ConnectToChrome(arg1:string):Promise<void>;

export function DebugAnalysis(arg1:string):Promise<string>;

export function DisconnectFromChrome():Promise<void>;

export function EnableNetwork(arg1:string):Promise<void>;

export function EnablePerformance(arg1:string):Promise<void>;

export function GetCachedResponseBody(arg1:string):Promise<string>;

export function GetChildNodes(arg1:string,arg2:number):Promise<Array<cdp.DOMNode>>;

export function GetConfig():Promise<cdp.Config>;

export function GetCookies(arg1:string):Promise<Array<cdp.CookieEntry>>;

export function GetDOMTree(arg1:string):Promise<cdp.DOMNode>;

export function GetLocalStorage(arg1:string):Promise<Array<cdp.StorageEntry>>;

export function GetNodePath(arg1:string,arg2:number):Promise<Array<number>>;

export function GetSessionStorage(arg1:string):Promise<Array<cdp.StorageEntry>>;

export function GetTabs():Promise<Array<cdp.TabInfo>>;

export function HighlightNode(arg1:string,arg2:number):Promise<void>;

export function IsConnected():Promise<boolean>;

export function PrintToPDF(arg1:string,arg2:boolean,arg3:boolean,arg4:number):Promise<string>;

export function ResetViewport(arg1:string):Promise<void>;

export function RunJS(arg1:string):Promise<void>;

export function SaveGeminiKey(arg1:string):Promise<void>;

export function SaveResponseBody(arg1:string,arg2:string):Promise<string>;

export function SearchDOM(arg1:string,arg2:string):Promise<Array<cdp.SearchResult>>;

export function SetViewport(arg1:string,arg2:number,arg3:number,arg4:number,arg5:boolean,arg6:boolean):Promise<void>;

export function SiteAudit(arg1:string):Promise<string>;
