// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreenshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureScreenshot'](arg1, arg2, arg3, arg4);
}

export function ClearHighlight(arg1) {
  return window['go']['main']['App']['ClearHighlight'](arg1);
}

export function ClearNetworkCache() {
  return window['go']['main']['App']['ClearNetworkCache']();
}

export function CollectWebVitals(arg1) {
  return window['go']['main']['App']['CollectWebVitals'](arg1);
}

export function ConnectToChrome(arg1) {
  return window['go']['main']['App']['ConnectToChrome'](arg1);
}

export function DebugAnalysis(arg1) {
  return window['go']['main']['App']['DebugAnalysis'](arg1);
}

export function DisconnectFromChrome() {
  return window['go']['main']['App']['DisconnectFromChrome']();
}

export function EnableNetwork(arg1) {
  return window['go']['main']['App']['EnableNetwork'](arg1);
}

export function EnablePerformance(arg1) {
  return window['go']['main']['App']['EnablePerformance'](arg1);
}

export function GetCachedResponseBody(arg1) {
  return window['go']['main']['App']['GetCachedResponseBody'](arg1);
}

export function GetChildNodes(arg1, arg2) {
  return window['go']['main']['App']['GetChildNodes'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCookies(arg1) {
  return window['go']['main']['App']['GetCookies'](arg1);
}

export function GetDOMTree(arg1) {
  return window['go']['main']['App']['GetDOMTree'](arg1);
}

export function GetLocalStorage(arg1) {
  return window['go']['main']['App']['GetLocalStorage'](arg1);
}

export function GetNodePath(arg1, arg2) {
  return window['go']['main']['App']['GetNodePath'](arg1, arg2);
}

export function GetSessionStorage(arg1) {
  return window['go']['main']['App']['GetSessionStorage'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function HighlightNode(arg1, arg2) {
  return window['go']['main']['App']['HighlightNode'](arg1, arg2);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function PrintToPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PrintToPDF'](arg1, arg2, arg3, arg4);
}

export function ResetViewport(arg1) {
  return window['go']['main']['App']['ResetViewport'](arg1);
}

export function RunJS(arg1) {
  return window['go']['main']['App']['RunJS'](arg1);
}

export function SaveGeminiKey(arg1) {
  return window['go']['main']['App']['SaveGeminiKey'](arg1);
}

export function SaveGeminiModel(arg1) {
  return window['go']['main']['App']['SaveGeminiModel'](arg1);
}

export function SaveResponseBody(arg1, arg2) {
  return window['go']['main']['App']['SaveResponseBody'](arg1, arg2);
}

export function SearchDOM(arg1, arg2) {
  return window['go']['main']['App']['SearchDOM'](arg1, arg2);
}

export function SetViewport(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetViewport'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SiteAudit(arg1) {
  return window['go']['main']['App']['SiteAudit'](arg1);
}
